nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@ojkelly/plugin-all.cjs
    spec: "https://yarn.build/latest"
  - path: .yarn/plugins/@yarnpkg/plugin-docker-build.cjs
    spec: "https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-docker-build.js"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
